create table dessert
(
    id bigint generated by default as identity,
    primary key (id)
);
create table drink
(
    addition_id bigint,
    id          bigint generated by default as identity,
    primary key (id)
);
create table drink_addition
(
    id          bigint generated by default as identity,
    another_add varchar(255),
    ice_cubes   varchar(255),
    lemon       varchar(255),
    primary key (id)
);
create table lunch
(
    dessert_id     bigint unique,
    id             bigint generated by default as identity,
    main_course_id bigint unique,
    primary key (id)
);
create table main_course
(
    id bigint generated by default as identity,
    primary key (id)
);
create table orders
(
    cuisine  tinyint check (cuisine between 0 and 2),
    drink_id bigint unique,
    id       bigint generated by default as identity,
    lunch_id bigint unique,
    primary key (id)
);
alter table if exists drink
    add constraint FKq5nf75wundyo4qfftxcq2au2u foreign key (addition_id) references drink_addition;
alter table if exists lunch
    add constraint FKirpwcxvg7h45d8i2jnfjbw0xj foreign key (dessert_id) references dessert;
alter table if exists lunch
    add constraint FKbxblo1fgvjcdsme7jeghge9hw foreign key (main_course_id) references main_course;
alter table if exists orders
    add constraint FK2ew9gskb43ivg6s6r67prjwe0 foreign key (drink_id) references drink;
alter table if exists orders
    add constraint FK6ar31e3oyrb5aej6pju0n09w foreign key (lunch_id) references lunch;
